### ISSUE TITLE
User images should be resized to a max size.

### ISSUE THREAD

**Issue by ffriedrich** [timomeinen/team-piazza#54]
Currently users can configure images which are rather large and thus prevent that all builds fit on the monitor. It should be possible to configure the max size of a user image and automatically resize to this size.

**Comment by timomeinen** [comment]
Hi Frank,
I created a new settings entry to define a maximum size for the portraits. It is limited to a maximum of 512px due to a limitation when using Gravatar. However, these sizes should fit most of the monitors. ;-) Hope this helps. Could you test the current build for me, please?
<img width="740" alt="bildschirmfoto 2015-10-20 um 19 51 57" src="https://cloud.githubusercontent.com/assets/212545/10622221/442d37ea-7786-11e5-9756-1f196d197014.png">

**Comment by timomeinen** [comment]
https://github.com/timomeinen/team-piazza/releases/tag/team-piazza-1.5

**Comment by frankbregulla1111** [comment]
Hi Timo,
this works perfectly. Thank you!
