### ISSUE TITLE
How to increase the auto-refresh time?

### ISSUE THREAD

**Issue by jaga43** [timomeinen/team-piazza#63]
How to increase the auto-refresh time?

**Comment by timomeinen** [comment]
We use the [Meta refresh](https://en.wikipedia.org/wiki/Meta_refresh) element to reload the page. A JavaScript approach would be much better. However, the page is refreshed every second, if a build is in progress. Otherwise after 10 seconds.

If you want to change the setting please change the value in the jsp pages. For Example:
[piazza-build-type-monitor.jsp](https://github.com/timomeinen/team-piazza/blob/master/team-piazza-server/src/main/resources/buildServerResources/piazza-build-type-monitor.jsp#L40)
